# Generated by Django 3.1.1 on 2020-09-12 21:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200912_1725'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
